# Generated by Django 3.2.7 on 2021-11-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenesCompra',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=300)),
                ('sku', models.IntegerField()),
                ('fechaEntrega', models.BigIntegerField()),
                ('cantidad', models.IntegerField()),
                ('urlNotificacion', models.CharField(max_length=500)),
                ('estado', models.CharField(max_length=200)),
            ],
        ),
    ]
