# Generated by Django 3.2.7 on 2021-12-08 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectogrupo2_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdenesCompra',
            new_name='OrdenCompra',
        ),
    ]
