# Generated by Django 3.2.7 on 2021-12-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectogrupo2_api', '0002_rename_ordenescompra_ordencompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='urlNotificacion',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
